backend:
  name: git-gateway
  branch: main
  repo: coffeewya/coffee-studio-next-ts
  base_url: https://coffee-studio-next-ts.netlify.app/
media_folder: public/uploads
public_folder: /uploads
# publish_mode: editorial_workflow
locale: zh-HK
i18n:
  structure: multiple_files
  locales: [zh-HK, en]
  default_locale: zh-HK

collections:
  - name: 'beans'
    label: 'Beans'
    label_singular: 'Bean'
    folder: 'src/beans'
    create: true
    i18n: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'product-page.template',
        }
      - {
          label: 'Product ID',
          name: 'pid',
          value_type: 'int',
          widget: 'number',
          i18n: duplicate,
        }
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          i18n: true,
          required: false,
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          i18n: duplicate,
          required: false,
        }
      - { label: 'Process', name: 'process', widget: 'string', i18n: true }
      - { label: 'Flavors', name: 'flavors', widget: 'string', i18n: true }
      - {
          label: 'Price',
          name: 'price',
          widget: 'number',
          i18n: duplicate,
          min: 1,
        }
      - {
          label: 'Weight(g)',
          name: 'weight',
          widget: 'number',
          default: 200,
          i18n: duplicate,
        }
      - {
          label: 'Sweetness',
          name: 'sweetness',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Acidity',
          name: 'acidity',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Bitterness',
          name: 'bitterness',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Finish',
          name: 'finish',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Floral',
          name: 'floral',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Herbs',
          name: 'herbs',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Fruits',
          name: 'fruits',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Nuts',
          name: 'nuts',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }
      - {
          label: 'Spices',
          name: 'spices',
          widget: 'select',
          i18n: duplicate,
          options: [1, 2, 3, 4, 5],
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page.template',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'home'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page.template',
            }
          - {
              label: 'Smoothies Section Heading',
              name: 'smoothiesHeading',
              widget: 'string',
            }
          - {
              label: 'Posts Section Heading',
              name: 'postsHeading',
              widget: 'string',
            }
          - {
              label: 'Contact Section Heading',
              name: 'contactHeading',
              widget: 'string',
            }
